---
- name: "Get the major version of python used to run ansible"
  command: "{{ ansible_python_interpreter | default('/usr/bin/python') }} -c 'import sys; print(sys.version_info.major)'"
  register: ansible_python_major
  changed_when: false

- debug:
    msg: "ansible_python_interpreter major version: {{ ansible_python_major.stdout }}"

- debug:
    msg: "Linux distribution is {{ ansible_distribution }}"

- name: "[Ubuntu] Install package dependencies for ansible MySQL modules"
  apt:
    name: "python3-mysqldb"
  when:
    - ansible_python_major.stdout == "3"
    - ansible_distribution == "Ubuntu"

- name: "[Alpine] Install package dependencies for ansible MySQL modules"
  community.general.apk:
    name: "py3-mysqlclient"
  when:
    - ansible_python_major.stdout == "3"
    - ansible_distribution == "Alpine"

- name: "[fsulib][Ubuntu] install mysql-client"
  apt:
    name: 
      - "mysql-client"
    state: "present"

- name: "[fsulib][Alpine] install mysql-client"
  community.general.apk:
    name: 
      - "mysql-client"
    state: "present"
