---

- name: "Make sure the MySQL users are present"
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default('pass') }}"
    append_privs: "{{ item.append_privs | default('false') }}"
    priv: "{{ item.priv | default('*.*:ALL') }}"
    state: "present"
    host: "{{ item.host | default('localhost') }}"
    login_host: "{{ item.login_host }}"
  with_items: "{{ mysql_users }}"

